# Application Name
spring.application.name=reimbursement-portal

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/reimbursement_db
spring.datasource.username=postgres
spring.datasource.password=Shaili
spring.datasource.driver-class-name= org.postgresql.Driver

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.port=8081
# Logging
logging.level.com.company.reimbursement=DEBUG
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n